final Andra
andrei-stoean/AutomationTestingAmazon pull request #4
Opened 2022-10-11 12:41 UTC by AndraP97

2022-10-12 14:26 UTC, postolachedan commented on src/test/java/org/example/SearchField.java
> +import org.openqa.selenium.support.ui.WebDriverWait;
imports not being used

2022-10-12 14:26 UTC, postolachedan commented on src/test/java/org/example/SearchField.java
> +import java.nio.charset.Charset;
imports not being used

2022-10-12 14:26 UTC, postolachedan commented on src/test/java/org/example/SearchField.java
> +        webDriver.manage().window().maximize();
could be moved to the setDriver() method

2022-10-12 14:26 UTC, postolachedan commented on src/test/java/org/example/SearchField.java
> +        String textTry= randomText();
variable name is not suggestive

2022-10-12 14:26 UTC, postolachedan commented on src/test/java/org/example/SearchField.java
> +        WebElement textErorr = webDriver.findElement(By.xpath("//*[@id=\"search\"]/div[1]/div[1]/div/span[3]/div[2]/div[1]/div/div/div/div[1]"));
a more relative xpath should probably be used

2022-10-12 14:26 UTC, postolachedan commented on src/test/java/org/example/SearchField.java
> +    private void searchFieldWrite() {
it's not clear from the method name what the test is doing

2022-10-12 14:26 UTC, postolachedan commented on src/test/java/org/example/SearchField.java
> +    private String randomText() {
method names should contain verbs. maybe generateRandomText() or getRandomText() could be better

2022-10-12 14:26 UTC, postolachedan commented on src/test/java/org/example/SearchField.java
> +    private void searchFieldInfo() {
method name is not very suggestive

2022-10-12 14:26 UTC, postolachedan commented on src/test/java/org/example/SearchField.java
> +        webDriver.manage().window().maximize();
could be moved to setDriver() method

2022-10-12 14:26 UTC, postolachedan commented on src/test/java/org/example/SearchField.java
> +        WebElement textSame = webDriver.findElement(By.xpath("//*[@id=\"search\"]/span/div/h1/div/div[1]/div/div/span[3]"));
variable name is not clear. xpath selector could be more relative.

2022-10-12 14:26 UTC, postolachedan commented on src/test/java/org/example/SearchField.java
> +    private void searchResults() {
method name is not suggestive.

2022-10-12 14:26 UTC, postolachedan commented on src/test/java/org/example/SearchField.java
> +        webDriver.manage().window().maximize();
could be moved to setDriver() method.

2022-10-12 14:26 UTC, postolachedan commented on src/test/java/org/example/SearchField.java
> +    private boolean search (List<WebElement> results) {
method name is not suggestive.

2022-10-14 12:16 UTC, andreidbr commented
It is good practice to add in PR description the text of the requirement that you are testing with this PR.

2022-10-14 12:30 UTC, andreidbr requested changes

2022-10-14 12:30 UTC, andreidbr commented on src/test/java/org/example/SearchField.java
>  public class SearchField {
Best practice is to add the Tests suffix to a class that contains @Tests -> SearchFieldTests

2022-10-14 12:30 UTC, andreidbr commented on src/test/java/org/example/SearchField.java
> +
You can remove this newline

2022-10-14 12:30 UTC, andreidbr commented on src/test/java/org/example/SearchField.java
> +        String textTry= "kgvgvkyuoum,8lhlmu,ybjhuvbhjvlb.hylubyhv;bhjlv,khn;biuh";
I would rename variable to randomTextForSearch or something a bit more suggestive

2022-10-14 12:30 UTC, andreidbr commented on src/test/java/org/example/SearchField.java
> +        WebElement textErorr = webDriver.findElement(By.xpath("//div[@class='a-row']"));
I would rename it to searchResultsMessage since it contains the message of the search results.

2022-10-14 12:30 UTC, andreidbr commented on src/test/java/org/example/SearchField.java
> +        WebElement textEqualsWithKey = webDriver.findElement(By.xpath("//span[@class=\"a-color-state a-text-bold\"]"));
Would also rename this element to something like searchResultMessage

2022-10-14 12:30 UTC, andreidbr commented on src/test/java/org/example/SearchField.java
> +    private void setDriver() {
Test methods as well as Before & After methods should be public

2022-10-14 12:30 UTC, andreidbr commented on src/test/java/org/example/SearchField.java
> +    private void searchResultsForSpecificKey() {
Rename it to SpecificWord since Key leads me to believe that you are searching with a single letter

2022-10-17 11:08 UTC, merged